// <auto-generated />
namespace PowerSell.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _22032024ModifiedOrdersConfirmed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_22032024ModifiedOrdersConfirmed));
        
        string IMigrationMetadata.Id
        {
            get { return "202403221205393_22-03-2024-ModifiedOrdersConfirmed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
