// <auto-generated />
namespace PowerSell.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _25032024OrderListToConfirmed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_25032024OrderListToConfirmed));
        
        string IMigrationMetadata.Id
        {
            get { return "202403251204596_25-03-2024-OrderListToConfirmed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
