// <auto-generated />
namespace PowerSell.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FixedOrdersAndSomeTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixedOrdersAndSomeTables));
        
        string IMigrationMetadata.Id
        {
            get { return "202403171339480_FixedOrdersAndSomeTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
